### ISSUE TITLE
Put it on maven

### ISSUE THREAD

**Issue by jbarros35** [Robbert1/boot-stateless-auth#2]
we can't use it without maven.
I can't run it inside my own tomcat. Its ask too much using some standard tools like tomcat or eclipse and maven? We need just check out and try to run not doing complex running tasks like gradle something, I can't run it without creating a project on Eclipse! Why can't you understand my very clear point?

**Comment by virgo47** [comment]
I can't resist after I checked your activity. Who is we? You? It seems you're checking some repos that may be of interest to you (I'm not sure) and then you file rather annoying issues instead of giving it a thought first. And it's not only about https://github.com/virgo47/restful-spring-security/issues/1

Please, tread lightly, it will help tremendously.

BTW: I made a lib once and it was pain to put it on Maven Central, but I did it. But I'd not do it with every little thing I wrote. You can still use it with Maven, you can download it, build it and use it from filesystem. Or fork it, add `pom.xml` and try it yourself.

Of course, Robbert1 may be nice to you, but it would still help everybody around if you learned how to file issues properly ([Example](http://coenjacobs.me/effective-bug-reports-on-github/)) instead of this shouting in the dark.

**Comment by jbarros35** [comment]
I only need a project clearly created on Eclipse with maven, nothing else. I'm using tomcat 7 and trying to debug and understand how it works. How it can be so hard to you for understanding?
Most of people even don't know what gradle is and we can't really understand and change your example using so sealed technologies like spring boot running from a command line and see what happens. Do you realize that or I'm not clear enough?
Opensource community doesn't have to be sealed traits and obscurity it must be CLEAR and easy to run and change! or else just close your repository and put it private only for you!

**Comment by jbarros35** [comment]
I'm using standard tools, wide acknowledge at java comunity, you're not. That's the problem!
